version: '2'

services:
  site:
    restart: always
    image: liuxh/siteapis
    depends_on:
    - cacheserver
    - dbserver
    ports:
    - "10080:6789"

    environment:
    - DEBUG=false
    - SECRET_KEY_BASE=this-should-be-chang-when-deploy-on-production

    - DB_ADAPTER=postgresql
    - DB_ENCODER=unicode
    - DB_HOST=dbserver
    - DB_PORT=5432
    - DB_USER=site
    - DB_PASS=site123
    - DB_NAME=sites_production

    - REDIS_HOST=cacheserver
    - REDIS_PORT=6379

  cacheserver:
    restart: always
    image: redis:latest
    command:
    - --loglevel warning
    volumes:
    - /Users/liuxinghao/Documents/wksapce/redis:/var/lib/redis:Z

  dbserver:
    restart: always
    image: postgres:9.6.2
    volumes:
    - /Users/liuxinghao/Documents/wksapce/postgresql:/var/lib/postgresql:Z

    ports:
    - "15432:5432"

    environment:
    - POSTGRES_USER=site
    - POSTGRES_PASSWORD=site123
    - POSTGRES_DB=sites_production
    - DB_EXTENSION=pg_trgm
