# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1dde553725f78c0432f664ce70144902266aafa3b8cef8dafbe80f6bac76c6030b81ce0d829d62a9e646311dfd03a7b26162231793683900cf62d7f31ef029

test:
  secret_key_base: cfb23c3eff686bbc43898ff5da5822a8e96a755321b7034f98d7e3755f71fef001bca6004d78b5d0b1076c26e4f2b6674074e8011ad6221756f999df0432d581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
